const Crash = () => {
    throw new Error('Error appeared :(')
}

export default Crash;